// Timer preset options (in seconds)
const CREATION_TIME_OPTIONS = [30, 60, 120, 180];
const JUDGING_TIME_OPTIONS = [15, 30, 45];

// Defaults
const DEFAULT_CREATION_TIME = 60;
const DEFAULT_JUDGING_TIME = 30;

// Game
const TOTAL_ROUNDS = 4;
const MAX_PLAYERS = 12;
const MIN_PLAYERS = 2;
const ROOM_CODE_LENGTH = 6;
const ROUND_RESULTS_DISPLAY_TIME = 10; // seconds to show round results
const TOTAL_POOKALAM_IMAGES = 10;

// Phases
const PHASES = {
  WAITING: 'WAITING',
  CREATION: 'CREATION',
  JUDGING: 'JUDGING',
  ROUND_RESULTS: 'ROUND_RESULTS',
  FINAL_RESULTS: 'FINAL_RESULTS',
};

module.exports = {
  CREATION_TIME_OPTIONS,
  JUDGING_TIME_OPTIONS,
  DEFAULT_CREATION_TIME,
  DEFAULT_JUDGING_TIME,
  TOTAL_ROUNDS,
  MAX_PLAYERS,
  MIN_PLAYERS,
  ROOM_CODE_LENGTH,
  ROUND_RESULTS_DISPLAY_TIME,
  TOTAL_POOKALAM_IMAGES,
  PHASES,
};
